import { useState, useEffect, useCallback, useRef } from 'react';

/**
 * useDashboardConfig — fetches and manages the full dashboard config per lens.
 *
 * The config is generated by the backend, which:
 *  1. Fetches charts?workflow_id=&lens_id= from the external API
 *  2. Passes chart_data + chart_insights + storyboard + overall_assessment to Claude/OpenAI
 *  3. Returns a complete config with storyboard tabs AND pages[].widgets — all data-driven
 */
export function useDashboardConfig(workflowId, lensId) {
  const [config,      setConfig]      = useState(null);
  const [loading,     setLoading]     = useState(false);
  const [error,       setError]       = useState(null);
  const [activeTabId, setActiveTabId] = useState(null);
  const configRef = useRef(null);

  const load = useCallback(async (regenerate = false) => {
    if (!workflowId) return;
    setLoading(true);
    setError(null);
    try {
      const lensParam = lensId ? `&lens_id=${lensId}` : '';
      const url = regenerate
        ? `/api/dashboard/${workflowId}?regenerate=1${lensParam}`
        : `/api/dashboard/${workflowId}?${lensParam.slice(1)}`;
      const res  = await fetch(url);
      const data = await res.json().catch(() => null);

      if (!res.ok) {
        // Backend returned an error JSON — try to surface a readable message
        const msg = data?.error ?? `Server error ${res.status}`;
        throw new Error(msg);
      }
      if (!data) throw new Error('Empty response from server');

      setConfig(data);
      configRef.current = data;
      // If the backend returned a fallback config due to an AI error,
      // set a soft warning (not a hard error — the dashboard still renders)
      if (data._error) {
        console.warn('[useDashboardConfig] Backend returned fallback config:', data._error);
        setError(`AI generation failed — showing estimated data. (${data._error})`);
      }
      if (!activeTabId && data.storyboard?.[0]) {
        setActiveTabId(data.storyboard[0].id);
      }
    } catch (err) {
      console.error('[useDashboardConfig] load failed:', err.message);
      setError(err.message);
    } finally {
      setLoading(false);
    }
  }, [workflowId, lensId]);

  useEffect(() => {
    if (workflowId) load();
  }, [workflowId, lensId]);

  const applyConfigUpdate = useCallback((newConfig) => {
    setConfig(newConfig);
    configRef.current = newConfig;
    // Keep active tab if it still exists
    const tabs = newConfig?.storyboard ?? [];
    if (tabs.length && !tabs.find((t) => t.id === activeTabId)) {
      setActiveTabId(tabs[0].id);
    }
  }, [activeTabId]);

  return { config, loading, error, activeTabId, setActiveTabId, reload: load, applyConfigUpdate };
}

/**
 * useDashboardChat — manages conversational chat.
 *
 * Key additions vs original:
 *  - messages[].chatWidgets: inline chart previews from AI response
 *  - pendingWidgets: flat list of all un-dismissed chat widget previews
 *  - promotePendingWidget(previewId): marks a preview as promoted (added to dashboard)
 *  - dismissPendingWidget(previewId): removes from pending list
 *  - sendMessage now accepts pendingWidgets so backend can reference them for "confirm" intents
 */
export function useDashboardChat(workflowId, lensId, onConfigUpdate, onBackgroundChange, onHtmlExport) {
  const [messages,       setMessages]       = useState([]);
  const [thinking,       setThinking]       = useState(false);
  const [chatError,      setChatError]      = useState(null);
  const [pendingWidgets, setPendingWidgets] = useState([]); // chatWidgets awaiting promotion

  // ── Local intent detection for background + export commands ───────────────
  function detectLocalIntent(text) {
    const t = text.toLowerCase();
    // Background change via URL
    const urlMatch = text.match(/(https?:\/\/\S+\.(jpg|jpeg|png|gif|webp|mp4|webm|mov))/i);
    if (urlMatch && /(background|hero|banner|page bg|change bg|set bg|update background)/i.test(t)) {
      const src = urlMatch[1];
      const type = /\.(mp4|webm|mov)$/i.test(src) ? 'video' : 'image';
      const target = /hero|banner|header/i.test(t) ? 'hero' : 'page';
      return { type: 'background', src, mediaType: type, target };
    }
    // HTML export
    if (/(export|generate|create|download|make).*html|html.*file|save.*html/i.test(t)) {
      return { type: 'html_export' };
    }
    return null;
  }

  const sendMessage = useCallback(async (text, currentPending = []) => {
    if (!workflowId || !text.trim()) return;

    // ── Handle local intents immediately (no API call) ─────────────────────
    const intent = detectLocalIntent(text);

    if (intent?.type === 'background') {
      const userMsg = { role: 'user', content: text, id: `u-${Date.now()}` };
      const assistantMsg = {
        role: 'assistant',
        content: `✅ Background updated to the ${intent.mediaType} you provided${intent.target === 'hero' ? ' in the hero section' : ''}. If you'd like to upload a local file instead, use the upload button.`,
        id: `a-${Date.now()}`,
        changesApplied: 0,
        chatWidgets: [],
        backgroundChange: { type: intent.mediaType, src: intent.src, target: intent.target },
      };
      setMessages((m) => [...m, userMsg, assistantMsg]);
      onBackgroundChange?.({ type: intent.mediaType, src: intent.src, target: intent.target });
      return;
    }

    if (intent?.type === 'html_export') {
      const userMsg = { role: 'user', content: text, id: `u-${Date.now()}` };
      const assistantMsg = {
        role: 'assistant',
        content: '📄 Generating your HTML file now — this combines the template design with all real API data…',
        id: `a-${Date.now()}`,
        changesApplied: 0,
        chatWidgets: [],
        triggerHtmlExport: true,
      };
      setMessages((m) => [...m, userMsg, assistantMsg]);
      onHtmlExport?.();
      return;
    }


    const userMsg = { role: 'user', content: text, id: `u-${Date.now()}` };
    setMessages((m) => [...m, userMsg]);
    setThinking(true);
    setChatError(null);

    try {
      const lensParam = lensId ? `?lens_id=${lensId}` : '';
      const res = await fetch(`/api/dashboard/${workflowId}/chat${lensParam}`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          message: text,
          conversationHistory: messages.slice(-6).map(({ role, content }) => ({ role, content })),
          // Pass any pending (not yet promoted) widgets so AI can reference them if user confirms
          pendingWidgets: currentPending.filter((pw) => !pw.promoted),
        }),
      });

      if (!res.ok) throw new Error(`HTTP ${res.status}`);
      const data = await res.json();

      // chatWidgets are the inline previews the AI wants to show in the conversation
      const chatWidgets = data.chatWidgets ?? [];

      const assistantMsg = {
        role: 'assistant',
        content: data.message,
        id: `a-${Date.now()}`,
        changesApplied: data.changesApplied ?? 0,
        chatWidgets,  // ← stored on the message for rendering in the conversation
      };
      setMessages((m) => [...m, assistantMsg]);

      // Add new chat widgets to the pending list
      if (chatWidgets.length > 0) {
        setPendingWidgets((prev) => [
          ...prev,
          ...chatWidgets.map((cw) => ({ ...cw, promoted: false, messageId: assistantMsg.id })),
        ]);
      }

      // If the AI made direct changes (theme update, remove widget, etc.), apply them
      if (data.config && (data.changesApplied ?? 0) > 0) {
        onConfigUpdate?.(data.config);
      }
    } catch (err) {
      setChatError(err.message);
      setMessages((m) => [
        ...m,
        {
          role: 'assistant',
          content: `Sorry, I couldn't process that: ${err.message}`,
          id: `err-${Date.now()}`,
          error: true,
          chatWidgets: [],
        },
      ]);
    } finally {
      setThinking(false);
    }
  }, [workflowId, lensId, messages, onConfigUpdate]);

  // Mark a chatWidget as promoted (added to dashboard)
  const promotePendingWidget = useCallback((previewId) => {
    setPendingWidgets((prev) =>
      prev.map((pw) => pw.previewId === previewId ? { ...pw, promoted: true } : pw)
    );
  }, []);

  // Remove a dismissed chatWidget from the pending list
  const dismissPendingWidget = useCallback((previewId) => {
    setPendingWidgets((prev) => prev.filter((pw) => pw.previewId !== previewId));
  }, []);

  return {
    messages,
    thinking,
    chatError,
    sendMessage,
    pendingWidgets,
    promotePendingWidget,
    dismissPendingWidget,
  };
}
