/**
 * HTML Template Registry
 * Each entry maps a template ID to its metadata and visual fingerprint.
 * The `file` path is relative to /public/templates/.
 */

export const HTML_TEMPLATES = [
  {
    id: 'template_01',
    name: 'Luxury Editorial',
    brand: 'Chanel',
    style: 'Premium Luxury',
    file: '/templates/template_01.html',
    primaryColor: '#944564',
    accentColor: '#C76F6E',
    bgColor: '#0f0a0d',
    textColor: '#ffffff',
    palette: ['#944564', '#C76F6E', '#4D97B4', '#1a0e14'],
    tags: ['Luxury', 'Dark', 'Editorial', 'Fashion'],
    description: 'High-fashion editorial layout with rich colour gradients',
    heroStyle: 'full-bleed-dark',
    chartStyle: 'minimal-light-on-dark',
  },
  {
    id: 'template_02',
    name: 'Creative Brand',
    brand: 'Cricut',
    style: 'Brand Intelligence',
    file: '/templates/template_02.html',
    primaryColor: '#7B2D8B',
    accentColor: '#E94E77',
    bgColor: '#f7f4fa',
    textColor: '#1a0a22',
    palette: ['#7B2D8B', '#E94E77', '#F4A261', '#2D7DD2'],
    tags: ['Creative', 'Vibrant', 'Brand', 'Craft'],
    description: 'Bold creative layout with vibrant accent palette',
    heroStyle: 'gradient-hero',
    chartStyle: 'vibrant-bars',
  },
  {
    id: 'template_03',
    name: 'Tech Intelligence',
    brand: '5G / Telecom',
    style: 'Consumer Mind',
    file: '/templates/template_03.html',
    primaryColor: '#0070CC',
    accentColor: '#00C8D4',
    bgColor: '#f0f4f8',
    textColor: '#0a1929',
    palette: ['#0070CC', '#00C8D4', '#7C4DFF', '#1A237E'],
    tags: ['Tech', 'Modern', 'Data-Heavy', 'Clean'],
    description: 'Clean tech layout ideal for telecom and connectivity brands',
    heroStyle: 'split-gradient',
    chartStyle: 'tech-blue',
  },
  {
    id: 'template_04',
    name: 'Beverage & FMCG',
    brand: 'Beverage Category',
    style: 'Category Intelligence',
    file: '/templates/template_04.html',
    primaryColor: '#E85D04',
    accentColor: '#FFBA08',
    bgColor: '#fffaf5',
    textColor: '#1b0000',
    palette: ['#E85D04', '#FFBA08', '#3A86FF', '#06A77D'],
    tags: ['FMCG', 'Warm', 'Category', 'Consumer'],
    description: 'Warm, energetic layout for FMCG and beverage intelligence',
    heroStyle: 'warm-overlay',
    chartStyle: 'warm-palette',
  },
  {
    id: 'template_05',
    name: 'Food & Nutrition',
    brand: 'F&B / GLP-1',
    style: 'Rebranding Intelligence',
    file: '/templates/template_05.html',
    primaryColor: '#2D6A4F',
    accentColor: '#74C69D',
    bgColor: '#f5fdf8',
    textColor: '#081c15',
    palette: ['#2D6A4F', '#74C69D', '#B7E4C7', '#40916C'],
    tags: ['Health', 'Green', 'Wellness', 'Nutrition'],
    description: 'Clean wellness layout with earthy green tones',
    heroStyle: 'nature-overlay',
    chartStyle: 'health-green',
  },
  {
    id: 'template_06',
    name: 'Healthcare & Pharma',
    brand: 'Medicare / Policy',
    style: 'Policy Intelligence',
    file: '/templates/template_06.html',
    primaryColor: '#003F88',
    accentColor: '#00B4D8',
    bgColor: '#f8fbff',
    textColor: '#001427',
    palette: ['#003F88', '#00B4D8', '#0096C7', '#023E8A'],
    tags: ['Healthcare', 'Policy', 'Trust', 'Clinical'],
    description: 'Professional clinical layout for healthcare and policy analysis',
    heroStyle: 'clinical-blue',
    chartStyle: 'medical-blue',
  },
  {
    id: 'template_07',
    name: 'PR Battle Light',
    brand: 'Telecom PR',
    style: 'Competitive Intelligence',
    file: '/templates/template_07.html',
    primaryColor: '#CC0000',
    accentColor: '#FF6B35',
    bgColor: '#ffffff',
    textColor: '#1a1a1a',
    palette: ['#CC0000', '#FF6B35', '#1A1A1A', '#F5F5F5'],
    tags: ['Competitive', 'Bold', 'PR', 'Light'],
    description: 'High-contrast light layout ideal for competitive PR analysis',
    heroStyle: 'bold-split',
    chartStyle: 'high-contrast',
  },
  {
    id: 'template_08',
    name: 'Sports & Events',
    brand: 'FIFA WC 2026',
    style: 'Event Intelligence',
    file: '/templates/template_08.html',
    primaryColor: '#C8102E',
    accentColor: '#FFD700',
    bgColor: '#f8f6ef',
    textColor: '#111111',
    palette: ['#C8102E', '#FFD700', '#003DA5', '#009473'],
    tags: ['Sports', 'Events', 'Dynamic', 'Global'],
    description: 'High-energy sports layout with bold international colours',
    heroStyle: 'sports-hero',
    chartStyle: 'sports-dynamic',
  },
  {
    id: 'template_09',
    name: 'Beauty & Reputation',
    brand: "L'Oreal",
    style: 'Reputation Intelligence',
    file: '/templates/template_09.html',
    primaryColor: '#C9184A',
    accentColor: '#FF4D6D',
    bgColor: '#fff0f3',
    textColor: '#370617',
    palette: ['#C9184A', '#FF4D6D', '#FF758C', '#FFCCD5'],
    tags: ['Beauty', 'Elegant', 'Reputation', 'Rose'],
    description: 'Elegant rose-toned layout for beauty and lifestyle brands',
    heroStyle: 'rose-gradient',
    chartStyle: 'beauty-rose',
  },
  {
    id: 'template_10',
    name: 'Pharma Intelligence',
    brand: 'Pfizer',
    style: 'Brand Intelligence',
    file: '/templates/template_10.html',
    primaryColor: '#003087',
    accentColor: '#00A1E4',
    bgColor: '#f5f7fa',
    textColor: '#001e5c',
    palette: ['#003087', '#00A1E4', '#009CDE', '#012169'],
    tags: ['Pharma', 'Enterprise', 'Trust', 'Scientific'],
    description: 'Scientific enterprise layout for pharmaceutical and life sciences',
    heroStyle: 'enterprise-clean',
    chartStyle: 'pharma-blue',
  },
  {
    id: 'template_11',
    name: 'B2B Enterprise',
    brand: 'Siemens',
    style: 'Digital Intelligence',
    file: '/templates/template_11.html',
    primaryColor: '#009999',
    accentColor: '#00CCCC',
    bgColor: '#f5fafa',
    textColor: '#001414',
    palette: ['#009999', '#00CCCC', '#006666', '#E6F7F7'],
    tags: ['B2B', 'Industrial', 'Enterprise', 'Digital'],
    description: 'Industrial enterprise layout for B2B and manufacturing intelligence',
    heroStyle: 'industrial-teal',
    chartStyle: 'teal-industrial',
  },
];

export const getTemplateById = (id) => HTML_TEMPLATES.find((t) => t.id === id) ?? null;
